# Generated by Cursor on 2026-04-09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200, verbose_name="会话标题")),
                (
                    "fastgpt_chat_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="FastGPT chatId",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "对话会话",
                "verbose_name_plural": "对话会话",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "user"), ("assistant", "assistant"), ("system", "system")],
                        max_length=16,
                        verbose_name="角色",
                    ),
                ),
                ("content", models.TextField(verbose_name="内容")),
                ("citations_json", models.JSONField(blank=True, default=list, verbose_name="引用数据")),
                ("raw_response_json", models.JSONField(blank=True, default=dict, verbose_name="原始响应")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="users.chatsession",
                        verbose_name="所属会话",
                    ),
                ),
            ],
            options={
                "verbose_name": "对话消息",
                "verbose_name_plural": "对话消息",
                "ordering": ["created_at", "id"],
            },
        ),
    ]
