# Generated by Cursor on 2026-04-20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_chatsession_chatmessage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SandboxRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("experiment_topic", models.CharField(max_length=120, verbose_name="实验课题")),
                ("image_name", models.CharField(blank=True, default="", max_length=200, verbose_name="镜像名称")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("starting", "启动中"),
                            ("running", "运行中"),
                            ("stopped", "已停止"),
                            ("failed", "启动失败"),
                        ],
                        default="starting",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("container_id", models.CharField(blank=True, default="", max_length=128, verbose_name="容器 ID")),
                ("web_port", models.PositiveIntegerField(blank=True, null=True, verbose_name="Web 端口")),
                ("started_at", models.DateTimeField(blank=True, null=True, verbose_name="启动时间")),
                ("stopped_at", models.DateTimeField(blank=True, null=True, verbose_name="停止时间")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sandbox_runs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="所属用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "实验沙箱运行",
                "verbose_name_plural": "实验沙箱运行",
                "ordering": ["-created_at"],
            },
        ),
    ]
