# Generated by Cursor on 2026-04-20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_sandboxrun"),
    ]

    operations = [
        migrations.AddField(
            model_name="sandboxrun",
            name="launch_error",
            field=models.TextField(blank=True, default="", verbose_name="启动错误"),
        ),
    ]
