# Generated by Django 4.2.30 on 2026-04-22 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_sandboxrun_launch_error"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExperimentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "experiment_name",
                    models.CharField(max_length=120, verbose_name="实验名称"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="启动时间"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "cover_image_b64",
                    models.TextField(
                        blank=True, default="", verbose_name="载体图(Base64)"
                    ),
                ),
                (
                    "stego_image_b64",
                    models.TextField(
                        blank=True, default="", verbose_name="隐写图(Base64)"
                    ),
                ),
                ("psnr", models.FloatField(blank=True, null=True, verbose_name="PSNR")),
                (
                    "histogram_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="直方图数据"
                    ),
                ),
                (
                    "bit_planes_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="位平面数据"
                    ),
                ),
                (
                    "source_text",
                    models.TextField(blank=True, default="", verbose_name="原始文本"),
                ),
                (
                    "extracted_text",
                    models.TextField(blank=True, default="", verbose_name="提取文本"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiment_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="所属用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "实验记录",
                "verbose_name_plural": "实验记录",
                "ordering": ["-created_at"],
            },
        ),
    ]
