# Generated by Django 4.2.30 on 2026-04-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_student_options_alter_student_grade_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={"verbose_name": "学生", "verbose_name_plural": "学生"},
        ),
        migrations.AlterField(
            model_name="student",
            name="grade",
            field=models.CharField(blank=True, max_length=32, verbose_name="年级"),
        ),
        migrations.AlterField(
            model_name="student",
            name="major",
            field=models.CharField(blank=True, max_length=100, verbose_name="专业"),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_id",
            field=models.CharField(
                blank=True, max_length=32, null=True, unique=True, verbose_name="学号"
            ),
        ),
    ]
