# Generated by Django 4.2.30 on 2026-04-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_student_options_alter_student_grade_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="experimentrecord",
            name="cpu_avg_percent",
            field=models.FloatField(
                blank=True, null=True, verbose_name="CPU平均占用(%)"
            ),
        ),
        migrations.AddField(
            model_name="experimentrecord",
            name="cpu_peak_percent",
            field=models.FloatField(
                blank=True, null=True, verbose_name="CPU峰值占用(%)"
            ),
        ),
        migrations.AddField(
            model_name="experimentrecord",
            name="duration_seconds",
            field=models.FloatField(blank=True, null=True, verbose_name="实验耗时(秒)"),
        ),
        migrations.AddField(
            model_name="experimentrecord",
            name="memory_avg_bytes",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="内存平均(bytes)"
            ),
        ),
        migrations.AddField(
            model_name="experimentrecord",
            name="memory_peak_bytes",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="内存峰值(bytes)"
            ),
        ),
    ]
